title: tetragir.com
baseurl: "https://tetragir.com"
permalink: /:categories/:title.html
url: "https://tetragir.com"

sass:
  style: compressed

date_format: "%m-%d-%Y"

markdown: kramdown

google_analytics: 
disqus_shortname:

